# Generated by Django 2.0.2 on 2018-03-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180303_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='publishing date'),
        ),
    ]
